# Copyright 2018, Oracle Corporation and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.

{{- if eq .Values.type "TRAEFIK" }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-traefik
  namespace: {{ .Values.wlsDomain.namespace }}
  annotations:
    kubernetes.io/ingress.class: traefik
    ingress.kubernetes.io/rule-type: PathPrefix
    weblogic.domainUID: {{ .Values.wlsDomain.domainUID }}
    {{- if .Values.rewriteTarget }}
    ingress.kubernetes.io/rewrite-target: {{ .Values.rewriteTarget }}
    {{- end }}
spec:
  rules:
  - host: {{ .Values.hostname }}
    http:
      paths:
      - path: {{ .Values.path }} 
        backend:
          serviceName: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.clusterName | lower | replace "_" "-" }}'
          servicePort: {{ .Values.wlsDomain.svcPort }}
  {{- if .Values.secretName }}
  tls:
  - secretName: {{ .Values.secretName }}
  {{- end }}
{{- end }}
